export const ADMIN_RELEASE='admin-pagination-2026-10-10-v1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0)/100);
const date=value=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}):'—';
const percent=value=>(Number(value||0)/100).toLocaleString('pt-BR')+'%';
const terms={active:'Ativo',paused:'Pausado',completed:'Concluído',cancelled:'Cancelado',purchase:'Compra própria',coupon:'Cupom',gift:'Presente',grant:'Concessão'};

export function whatsappUrl(value){
 let digits=String(value||'').replace(/\D/g,'');
 if(digits.length<10||digits.length>15)return null;
 if(digits.length===10||digits.length===11)digits='55'+digits;
 return 'https://wa.me/'+digits;
}
export function adminContact(value){
 const href=whatsappUrl(value);
 return href?`<a class="admin-whatsapp" href="${href}" target="_blank" rel="noopener noreferrer">WhatsApp: ${esc(value)}</a>`:'<small class="muted">WhatsApp não informado</small>';
}
const attribute=(scope,key)=>`data-admin-scope="${scope}" data-key="${esc(key)}"`;
export function pageControls(result,key,scope='main'){
 if(!result)return '';
 const {total,page,page_size: size,total_pages: pages}=result;
 const first=total?(page-1)*size+1:0,last=Math.min(page*size,total);
 return `<nav class="admin-pagination" aria-label="Paginação de ${esc(key)}"><span role="status">${first}–${last} de ${total} registros · Página ${page} de ${pages}</span><div class="admin-pagination-controls"><label>Por página <select data-admin-size ${attribute(scope,key)} aria-label="Registros por página">${[10,20,50,100].map(n=>`<option value="${n}" ${Number(size)===n?'selected':''}>${n}</option>`).join('')}</select></label><button class="secondary" data-action="admin-page" ${attribute(scope,key)} data-page="1" ${page<=1?'disabled':''} aria-label="Primeira página">«</button><button class="secondary" data-action="admin-page" ${attribute(scope,key)} data-page="${page-1}" ${page<=1?'disabled':''}>Anterior</button><button class="secondary" data-action="admin-page" ${attribute(scope,key)} data-page="${page+1}" ${page>=pages?'disabled':''}>Próxima</button><button class="secondary" data-action="admin-page" ${attribute(scope,key)} data-page="${pages}" ${page>=pages?'disabled':''} aria-label="Última página">»</button></div></nav>`;
}
export function listTools(query,key,statuses=[],scope='main'){
 return `<div class="admin-list-tools"><form data-admin-search="${esc(key)}" data-admin-scope="${scope}" role="search"><label class="sr-only" for="${scope}-${key}-search">Buscar registros</label><input id="${scope}-${key}-search" name="search" maxlength="200" value="${esc(query.search)}" placeholder="Buscar nome, contato ou registro"><button class="secondary" type="submit">Buscar</button></form>${statuses.length?`<select data-admin-status ${attribute(scope,key)} aria-label="Filtrar status">${[['','Todos'],...statuses].map(([value,label])=>`<option value="${esc(value)}" ${query.status===value?'selected':''}>${esc(label)}</option>`).join('')}</select>`:''}</div>`;
}
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`;
export function adminProfileView(profile,editHtml=''){
 const d=profile.detail,u=d.user,key=profile.tab,page=profile.pages[key],query=profile.queries[key]||{search:'',status:''};
 const tabs=[['overview','Resumo'],['positions','Produtos'],['affiliates','Afiliados'],['commissions','Comissões'],['edit','Editar perfil']];
 let body='';
 if(key==='overview')body=`<div class="admin-profile-metrics">${[['Saldo disponível',u.wallet.available_cents],['Saldo reservado',u.wallet.reserved_cents],['Capital em produtos ativos',d.invested_cents],['Rendimentos recebidos',d.earned_cents],['Comissões recebidas',d.commissions_cents]].map(([label,value])=>`<article class="metric"><span>${label}</span><strong>${money(value)}</strong></article>`).join('')}</div><div class="admin-profile-facts"><p>Produtos: <strong>${d.products_count}</strong> · Ativos: <strong>${d.active_products}</strong></p><p>Cadastro: ${date(u.created_at)}</p><p>E-mail ${u.email_confirmed_at?'confirmado':'não confirmado'}</p><p>Indicador: ${d.sponsor?`<button class="text" data-action="admin-user" data-id="${esc(d.sponsor.id)}">${esc(d.sponsor.full_name)}</button>`:'Sem indicador'}</p></div><h3>Equipe e comissões por nível</h3><div class="admin-level-cards">${d.levels.map(l=>`<button class="admin-level-card" data-action="admin-profile-level" data-level="${l.level}"><strong>Nível ${l.level}</strong><span>${l.total} afiliados · ${l.active} ativos</span><span>${money(l.commissions_cents)} recebidos</span></button>`).join('')}</div>`;
 if(key==='positions')body=listTools(query,key,[['active','Ativos'],['paused','Pausados'],['completed','Concluídos'],['cancelled','Cancelados']],'profile')+table(['Produto / origem','Capital / recebido','Taxa / prazo','Status','Devolução','Ações'],(page?.items||[]).map(p=>`<tr><td><strong>${esc(p.name)}</strong><small>${esc(terms[p.source]||p.source||'—')}</small></td><td>${money(p.principal_cents)}<small>Rendimentos ${money(p.earned_cents)}</small></td><td>${percent(p.daily_bps)} / ${p.duration_days} dias<small>${p.paid_periods} períodos pagos</small></td><td>${esc(terms[p.status]||p.status)}</td><td>${p.principal_returned?'Devolvido':p.return_principal?'Prevista no vencimento':'Não prevista'}</td><td><button class="text" data-action="admin-position" data-id="${esc(p.id)}">Editar</button></td></tr>`).join(''))+pageControls(page,key,'profile');
 if(key==='affiliates')body=`<div class="segmented admin-profile-levels" aria-label="Nível dos afiliados">${d.levels.map(l=>`<button class="${profile.level===l.level?'selected':''}" data-action="admin-profile-level" data-level="${l.level}">Nível ${l.level} · ${l.total}</button>`).join('')}</div><p class="muted">A comissão abaixo é o valor já recebido por ${esc(u.full_name)} a partir daquele afiliado.</p>`+listTools(query,key,[['active','Com produto ativo'],['inactive','Sem produto ativo']],'profile')+table(['Afiliado / WhatsApp','Produtos do afiliado','Comissão gerada','Perfil'],(page?.items||[]).map(t=>`<tr><td><strong>${esc(t.full_name)}</strong>${adminContact(t.whatsapp)}<small>${t.blocked?'Acesso suspenso · ':''}${t.active?'Com produto ativo':'Sem produto ativo'}</small></td><td>${t.products.map(p=>`<small>${esc(p.name)} · ${esc(terms[p.status]||p.status)}</small>`).join('')||'<small>Sem produtos</small>'}${t.products_count?`<button class="text" data-action="admin-affiliate-products" data-id="${esc(t.id)}">Ver todos (${t.products_count})</button>`:''}</td><td>${money(t.commission_cents)}</td><td><button class="text" data-action="admin-user" data-id="${esc(t.id)}">Ver perfil</button></td></tr>`).join(''))+pageControls(page,key,'profile');
 if(key==='commissions')body=`<p>Total já recebido: <strong>${money(d.commissions_cents)}</strong></p>`+listTools(query,key,[['1','Nível 1'],['2','Nível 2'],['3','Nível 3']],'profile')+table(['Afiliado / contato','Nível','Produto','Comissão recebida','Data'],(page?.items||[]).map(c=>`<tr><td><button class="text" data-action="admin-user" data-id="${esc(c.source_user_id)}">${esc(c.source_name)}</button>${adminContact(c.source_whatsapp)}</td><td>${c.level}</td><td>${esc(c.product_name)}</td><td>${money(c.amount_cents)}</td><td>${date(c.created_at)}</td></tr>`).join(''))+pageControls(page,key,'profile');
 if(key==='edit')body=editHtml;
 return `<div class="admin-profile-header"><div><strong>${esc(u.full_name)}</strong><small>${esc(u.email||'E-mail não informado')}</small>${adminContact(u.whatsapp)}<small>${u.blocked?'Acesso suspenso':'Acesso liberado'}${u.is_admin?' · Administrador':''}</small></div><div class="button-row"><button class="secondary" data-action="admin-balance" data-id="${esc(u.id)}">Ajustar saldo</button><button class="secondary" data-action="admin-add-position" data-id="${esc(u.id)}">Conceder produto</button></div></div><nav class="admin-tabs" aria-label="Seções do perfil">${tabs.map(([tab,label])=>`<button class="${key===tab?'selected':''}" data-action="admin-profile-tab" data-tab="${tab}">${label}</button>`).join('')}</nav><section class="admin-profile-content">${body}</section>`;
}
