export const ANNOUNCEMENT_RELEASE='dashboard-announcement-admin-2026-10-11-v1';
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validAnnouncementUrl(value,asset=false){
 if(typeof value!=='string'||value.length>2000||/[\s<>"\\]/.test(value))return false;
 if(asset&&/^\/assets\/[A-Za-z0-9][A-Za-z0-9/_.-]*$/.test(value)&&!value.includes('..'))return true;
 try{const url=new URL(value);return url.protocol==='https:'&&/^https:\/\//.test(value)&&!url.username&&!url.password&&!!url.hostname;}catch{return false;}
}
export function normalizeAnnouncement(value){
 if(!value||value.id!=='dashboard'||!Number.isSafeInteger(value.revision)||value.revision<1||typeof value.title!=='string'||!value.title.trim()||value.title.length>120||typeof value.message!=='string'||!value.message.trim()||value.message.length>4000||typeof value.active!=='boolean'||typeof value.show_popup!=='boolean'||typeof value.show_card!=='boolean'||!Array.isArray(value.buttons)||value.buttons.length>5)return null;
 if(value.image_url&&!validAnnouncementUrl(value.image_url,true))return null;
 if(value.buttons.some(b=>!b||typeof b.label!=='string'||!b.label.trim()||b.label.length>60||!validAnnouncementUrl(b.url)||!['primary','secondary'].includes(b.style)))return null;
 return {...value,image_url:value.image_url||null,image_alt:String(value.image_alt||'').slice(0,160)};
}
export const announcementKey=notice=>notice?notice.id+':'+notice.revision:null;
export function announcementContent(notice){
 return `${notice.image_url?`<img class="announcement-image" src="${escapeHtml(notice.image_url)}" alt="${escapeHtml(notice.image_alt||notice.title)}" referrerpolicy="no-referrer">`:''}<div class="announcement-message">${escapeHtml(notice.message)}</div><div class="announcement-buttons">${notice.buttons.map(b=>`<a class="${b.style} community-join" href="${escapeHtml(b.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(b.label)}</a>`).join('')}</div>`;
}
export function announcementButtonFields(button={label:'',url:'',style:'primary'}){
 return `<section class="announcement-button-editor" data-announcement-button><label>Texto do botão<input name="button_label" value="${escapeHtml(button.label)}" maxlength="60" required></label><label>Link HTTPS<input name="button_url" type="url" value="${escapeHtml(button.url)}" maxlength="2000" required placeholder="https://..."></label><label>Estilo<select name="button_style"><option value="primary" ${button.style==='primary'?'selected':''}>Destaque</option><option value="secondary" ${button.style==='secondary'?'selected':''}>Secundário</option></select></label><div class="button-row"><button type="button" class="text" data-announcement-move="up">Subir</button><button type="button" class="text" data-announcement-move="down">Descer</button><button type="button" class="text danger" data-announcement-remove>Remover</button></div></section>`;
}
export function announcementEditor(notice){
 if(!notice)return '<section class="panel"><p>Não foi possível carregar o aviso.</p></section>';
 return `<div class="announcement-admin" data-announcement-release="${ANNOUNCEMENT_RELEASE}"><section class="panel"><h2>Aviso da dashboard</h2><p class="muted">Salve para publicar o conteúdo. Uma alteração cria uma nova versão e permite que todos vejam o aviso novamente.</p><form data-form="announcement" data-revision="${notice.revision}"><label>Título<input name="title" value="${escapeHtml(notice.title)}" maxlength="120" required></label><label>Mensagem<textarea name="message" rows="7" maxlength="4000" required>${escapeHtml(notice.message)}</textarea></label><div class="form-grid"><label>Imagem opcional<input name="image_url" value="${escapeHtml(notice.image_url||'')}" maxlength="2000" placeholder="URL HTTPS ou /assets/imagem.png"></label><label>Descrição da imagem<input name="image_alt" value="${escapeHtml(notice.image_alt||'')}" maxlength="160"></label></div><div class="announcement-display"><label class="check-label"><input type="checkbox" name="active" ${notice.active?'checked':''}> Aviso ativo</label><label class="check-label"><input type="checkbox" name="show_popup" ${notice.show_popup?'checked':''}> Abrir automaticamente ao entrar na dashboard</label><label class="check-label"><input type="checkbox" name="show_card" ${notice.show_card?'checked':''}> Mostrar também um cartão na dashboard</label></div><h3>Botões</h3><div id="announcement-buttons-editor">${notice.buttons.map(announcementButtonFields).join('')}</div><button type="button" class="secondary" id="announcement-add-button">Adicionar botão</button><label>Grupo oficial do WhatsApp<input name="whatsapp_group" type="url" value="${escapeHtml(notice.whatsapp_group||'')}" placeholder="https://chat.whatsapp.com/..." maxlength="2000"></label><small>Este campo atualiza o botão flutuante da comunidade. Configure o link de cada botão do aviso acima.</small><div class="announcement-save-row"><button class="primary" type="submit">Salvar e publicar aviso</button><button class="secondary" type="button" id="announcement-republish">Publicar novamente</button></div><p class="form-error" role="alert"></p><p class="muted">Versão publicada: ${notice.revision}</p></form></section><section class="panel announcement-preview-panel"><h2>Visualização do aviso</h2><div id="announcement-preview" class="announcement-preview"></div></section></div>`;
}
export function readAnnouncementForm(form){
 const get=name=>form.querySelector(`[name="${name}"]`);
 return {title:get('title').value.trim(),message:get('message').value.trim(),image_url:get('image_url').value.trim()||null,image_alt:get('image_alt').value.trim(),active:get('active').checked,show_popup:get('show_popup').checked,show_card:get('show_card').checked,whatsapp_group:get('whatsapp_group').value.trim(),buttons:[...form.querySelectorAll('[data-announcement-button]')].map(row=>({label:row.querySelector('[name=button_label]').value.trim(),url:row.querySelector('[name=button_url]').value.trim(),style:row.querySelector('[name=button_style]').value}))};
}
