import './style.css';
import {client,enterDemo,leaveDemo,isDemo,resetDemo,snapshot,action,payment,toCents,dailyYield,payout} from './lib/store.js';
const app=document.querySelector('#app');const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0)/100);
const date=s=>s?new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const percent=n=>(Number(n)/100).toLocaleString('pt-BR')+'%';
const names={dashboard:'Visão geral',products:'Produtos',positions:'Meus produtos',team:'Minha equipe',wallet:'Carteira',admin:'Administração'};
const labels={production:'Produção',distribution:'Distribuição',active:'Ativo',paused:'Pausado',completed:'Concluído',cancelled:'Cancelado',pending:'Pendente',requested:'Aguardando aprovação',approved:'Aprovado',processing:'Processando',rejected:'Rejeitado',failed:'Falhou',review:'Em análise',creating:'Criando cobrança',refunded:'Estornado'};
const paths={dashboard:'M3 10l9-7 9 7v11H3z M9 21v-8h6v8',products:'M3 7l9-4 9 4-9 5z M3 7v10l9 4 9-4V7 M12 12v9',positions:'M5 4h14v17H5z M8 8h8 M8 12h8 M8 16h5',team:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M18 8a3 3 0 0 1 0 6 M22 21v-2a4 4 0 0 0-3-4',wallet:'M3 5h17v15H3z M15 10h7v6h-7z M18 13h1',admin:'M12 3l8 4v6c0 5-8 9-8 9s-8-4-8-9V7z M9 12l2 2 4-4',plus:'M12 5v14 M5 12h14',check:'M4 12l5 5L20 6',copy:'M8 8h13v13H8z M16 8V3H3v13h5',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1 1 M18 18l1 1 M5 19l1-1 M18 6l1-1',chat:'M21 11a9 9 0 1 1-17 6l-1 4 4-1a9 9 0 0 0 14-9 M7 9h10 M7 13h7',logout:'M9 3H3v18h6 M13 7l5 5-5 5 M7 12h11',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6'};
const icon=n=>`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.products}"/></svg>`;
let data=null,route='dashboard',category='production',level=1,adminTab='overview',q='',busy=false,recovery=false,authMode='login',bannerIndex=0;
try{document.documentElement.dataset.theme=localStorage.getItem('eletrify-theme')||'dark';}catch{}
const ownPositions=()=>data.positions.filter(p=>p.user_id===data.profile.id);
const maturity=p=>new Date(Date.parse(p.created_at)+p.duration_days*86400000).toISOString();
const principalSummary=p=>p.principal_returned?'Capital devolvido: '+money(p.principal_cents):p.status==='cancelled'?'Contrato cancelado':p.return_principal?'Capital a devolver: '+money(p.principal_cents):'Sem devolução de capital neste contrato';
const status=s=>`<span class="status ${esc(s)}">${esc(labels[s]||s)}</span>`;
const empty=(title,text)=>`<div class="empty">${icon('products')}<h3>${title}</h3><p>${text}</p></div>`;
const button=(text,act,extra='',cls='primary')=>`<button class="${cls}" data-action="${act}" ${extra}>${text}</button>`;
const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,value,opts)=>`<label>${label}<select name="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
function toast(text,error=false){const el=$('#toast');if(!el)return;el.textContent=text;el.className='toast visible '+(error?'error':'');setTimeout(()=>el.classList.remove('visible'),5500);}
function errorMessage(e){if(/wallets_available_cents_check/.test(e.message))return 'Saldo insuficiente para esta operação.';return e.message||'Não foi possível concluir. Tente novamente.';}
const canAdmin=()=>data?.profile?.is_admin===true&&data.profile.blocked===false;
async function refresh(){
 data=await snapshot(false);
 if(route==='admin'&&canAdmin()){
  try{data=await snapshot(true);}catch(e){data=await snapshot(false);if(canAdmin())throw e;}
 }
 render();
}
function theme(){const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem('eletrify-theme',t);}catch{}if(data)render();else renderAuth();}
function navigate(r){route=r;q='';history.replaceState(null,'','#/'+r);refresh().catch(e=>toast(errorMessage(e),true));window.scrollTo(0,0);}
function nav(){return Object.entries(names).filter(([k])=>k!=='admin'||canAdmin()).map(([k,label])=>`<button data-action="navigate" data-route="${k}" class="nav-item ${route===k?'selected':''}">${icon(k)}<span>${k==='dashboard'?'Início':label}</span></button>`).join('');}
function render(){
 if(route==='admin'&&!canAdmin()){route='dashboard';history.replaceState(null,'','#/dashboard');}
 const scroll=window.scrollY;
 app.innerHTML=`${isDemo()?'<div class="demo-bar"><span>Demonstração · dados e valores ilustrativos · nenhum pagamento real</span><button data-action="reset-demo">Reiniciar</button><button data-action="logout">Sair</button></div>':''}<div class="shell"><aside class="sidebar"><a href="#/dashboard" class="logo"><img src="/assets/logo.png" alt="Eletrify"></a><div class="workspace-label">ÁREA DO USUÁRIO</div><nav>${nav()}</nav><div class="sidebar-foot"><div class="mini-brand">Mobilidade em movimento.</div><button data-action="theme">${icon('sun')} Alterar tema</button><button data-action="logout">${icon('logout')} Sair</button></div></aside><main class="workspace"><header class="topbar"><div class="mobile-logo"><img src="/assets/logo.png" alt="Eletrify"></div><div class="breadcrumb">Eletrify <span>/ ${names[route]}</span></div><div class="top-actions"><button class="icon-btn" data-action="refresh" aria-label="Atualizar dados">↻</button><button class="icon-btn" data-action="theme" aria-label="Alterar tema">${icon('sun')}</button><button class="profile-btn" data-action="profile"><span class="avatar">${data.profile.avatar_url&&/^https:\/\//.test(data.profile.avatar_url)?`<img src="${esc(data.profile.avatar_url)}" alt="Foto do perfil">`:esc(data.profile.full_name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</span><span>${esc(data.profile.full_name.split(' ')[0])}</span></button></div></header><div class="page">${({dashboard,products:productPage,positions:positionPage,team:teamPage,wallet:walletPage,admin:adminPage}[route]||dashboard)()}</div><footer class="page-footer">© ${new Date().getFullYear()} Eletrify <span>Valores em reais · Horário de Brasília</span></footer></main></div><nav class="bottom-nav">${nav()}</nav><button class="whatsapp-float" data-action="whatsapp" aria-label="Abrir comunidade WhatsApp">${icon('chat')}</button><dialog id="modal"></dialog><div id="toast" class="toast" role="status" aria-live="polite"></div>`;
 bind();window.scrollTo(0,scroll);
}
function heading(title,subtitle='',tools=''){return `<div class="page-heading"><div><span class="eyebrow">ELETRIFY</span><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${tools}</div>`;}
function stats(){const ps=ownPositions();const invested=ps.filter(p=>p.status==='active').reduce((n,p)=>n+p.principal_cents,0);const future=ps.filter(p=>p.status==='active').reduce((n,p)=>n+dailyYield(p.principal_cents,p.daily_bps)*Math.max(0,p.duration_days-p.paid_periods),0);return {invested,future,earned:ps.reduce((n,p)=>n+p.earned_cents,0),daily:ps.filter(p=>p.status==='active').reduce((n,p)=>n+dailyYield(p.principal_cents,p.daily_bps),0)};}
function dashboard(){const s=stats();const banners=[['Um futuro elétrico.<br>Novas possibilidades.','/assets/hero.png'],['Produção e tecnologia<br>em cada detalhe.','/assets/moto-estrutura-bateria-motor.png'],['Distribuição que<br>conecta caminhos.','/assets/lote-tres-carros-eletricos.png']];const b=banners[bannerIndex];return `${heading('Olá, '+esc(data.profile.full_name.split(' ')[0])+'.','Acompanhe seus produtos e movimentações.',button(icon('plus')+' Adicionar saldo','deposit'))}<div class="dashboard-top"><section class="balance-card"><div class="card-label">Saldo disponível</div><div class="balance">${money(data.wallet.available_cents)}</div><div class="balance-details">${money(data.wallet.reserved_cents)} reservados para saques</div><div class="button-row">${button('Adicionar saldo','deposit')}${button('Sacar','withdraw','','secondary')}</div><div class="balance-bottom">Carteira Pix <span>BRL</span></div></section><section class="hero-card"><div class="hero-copy"><span class="eyebrow">CONECTADA AO FUTURO</span><h2>${b[0]}</h2><button class="small-light" data-action="navigate" data-route="products">Conhecer produtos</button><div class="dots">${banners.map((_,i)=>`<button aria-label="Banner ${i+1}" data-action="banner" data-index="${i}" class="${i===bannerIndex?'selected':''}"></button>`).join('')}</div></div><img src="${b[1]}" alt="Ilustração conceitual Eletrify"></section></div><div class="metrics">${[['Capital em produtos',s.invested,'Produtos ativos'],['Rendimentos recebidos',s.earned,'Total realizado'],['Ganhos futuros estimados',s.future,'Conforme as condições contratadas']].map(([label,val,sub])=>`<article class="metric"><div>${label}</div><strong>${money(val)}</strong><small>${sub}</small></article>`).join('')}</div><section class="panel"><div class="section-heading"><div><h2>Seus produtos em movimento</h2><p>${ownPositions().filter(p=>p.status==='active').length} ativos · ${money(s.daily)} previstos por período de 24h</p></div><button class="text" data-action="navigate" data-route="positions">Ver meus produtos</button></div>${ownPositions().length?ownPositions().slice(0,2).map(positionRow).join(''):empty('Seu primeiro produto começa aqui','Explore o catálogo e confira as condições.')}</section><div class="section-heading"><div><h2>Explore o catálogo</h2><p>Projetos de produção e distribuição.</p></div><button class="text" data-action="navigate" data-route="products">Ver todos</button></div><div class="product-grid">${data.products.filter(p=>p.active).slice(0,4).map(productCard).join('')||empty('Catálogo em preparação','Novos produtos aparecerão por aqui.')}</div>`;}
function tabs(kind){return `<div class="segmented"><button data-action="category" data-category="production" class="${category==='production'?'selected':''}">Produção</button><button data-action="category" data-category="distribution" class="${category==='distribution'?'selected':''}">Distribuição</button></div>`;}
function productCard(p){const daily=dailyYield(p.price_cents,p.daily_bps);return `<article class="product-card"><div class="product-art"><span class="category-tag">${labels[p.category]}</span><img loading="lazy" src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="product-body"><h3>${esc(p.name)}</h3><div class="product-price">${money(p.price_cents)}<small>à vista</small></div><div class="product-terms"><div><strong>${percent(p.daily_bps)}</strong><span>por 24h</span></div><div><strong>${p.duration_days} dias</strong><span>de duração</span></div><div><strong>${money(daily)}</strong><span>por período</span></div></div><button data-action="product" data-id="${p.id}" class="primary">Conhecer e comprar</button></div></article>`;}
function productPage(){const ps=data.products.filter(p=>p.active&&p.category===category&&p.name.toLowerCase().includes(q.toLowerCase()));return `${heading('Produtos','Conheça as condições de cada projeto antes de adquirir.')}<div class="filters">${tabs()}<form id="search-form"><label class="search">${icon('search')}<input name="search" value="${esc(q)}" placeholder="Buscar produto" aria-label="Buscar produto"><button type="submit">Buscar</button></label></form></div><div class="product-grid">${ps.map(productCard).join('')||empty('Nenhum produto encontrado','Tente outra categoria ou pesquisa.')}</div><p class="footnote">As imagens são conceituais. Projeções dependem das condições do produto e não representam valores já recebidos.</p>`;}
function positionRow(p){const pc=Math.min(100,p.paid_periods/p.duration_days*100);return `<article class="position-row"><div class="position-art"><img src="${esc(p.image)}" alt=""></div><div class="position-main"><div class="position-title"><h3>${esc(p.name)}</h3>${status(p.status)}</div><span class="muted">${labels[p.category]} · adquirido em ${date(p.created_at)}</span><div class="progress" aria-label="${p.paid_periods} de ${p.duration_days} períodos pagos"><span style="width:${pc}%"></span></div><small>${p.paid_periods}/${p.duration_days} períodos pagos</small></div><div class="position-value"><span>Já recebido</span><strong>${money(p.earned_cents)}</strong><small>Rendimentos restantes: ${money(['active','paused'].includes(p.status)?dailyYield(p.principal_cents,p.daily_bps)*Math.max(0,p.duration_days-p.paid_periods):0)}</small><small>${principalSummary(p)}</small><button class="text" data-action="position" data-id="${p.id}">Ver detalhes</button></div></article>`;}
function positionPage(){const ps=ownPositions().filter(p=>p.category===category);const owned=ownPositions();const avg=owned.length?owned.reduce((n,p)=>n+p.principal_cents,0)/owned.length:0;let rec=data.products.filter(p=>p.active&&p.price_cents<=Math.max(data.wallet.available_cents,avg*1.8)&&!owned.some(x=>x.product_id===p.id));rec=rec.sort((a,b)=>Math.abs(a.price_cents-avg)-Math.abs(b.price_cents-avg)).slice(0,3);return `${heading('Meus produtos','Pagamentos a cada 24h desde a aquisição, conforme o contrato.')}<div class="filters">${tabs()}</div><section class="panel">${ps.map(positionRow).join('')||empty('Você ainda não tem produtos nesta categoria','Visite o catálogo para conhecer as opções.')}</section><div class="section-heading"><div><h2>Opções para explorar</h2><p>Considerando seu saldo e o valor dos produtos que você já adquiriu.</p></div></div><div class="product-grid">${rec.map(productCard).join('')||empty('Explore mais produtos','Veja todas as opções disponíveis no catálogo.')}</div>`;}
function teamPage(){const ts=data.team.filter(t=>t.level===level&&t.full_name.toLowerCase().includes(q.toLowerCase()));const commission=data.commissions.reduce((n,c)=>n+c.amount_cents,0);const link=location.origin+'/?ref='+encodeURIComponent(data.profile.referral_code);return `${heading('Minha equipe','Acompanhe indicações e comissões da primeira compra.')}<div class="team-top"><section class="invite-card"><span class="eyebrow">CRESÇA EM EQUIPE</span><h2>Seu convite, novas conexões.</h2><p>Compartilhe seu link pessoal para identificar seus convidados.</p><div class="copy-line"><input readonly value="${esc(link)}" aria-label="Link de indicação"><button data-action="copy" data-copy="${esc(link)}">${icon('copy')} Copiar</button></div><button class="text" data-action="invite-tips">Dicas para apresentar a Eletrify</button></section><section class="panel team-summary"><h3>Resumo da equipe</h3><div class="mini-metrics"><div><strong>${data.team.length}</strong><span>Pessoas</span></div><div><strong>${data.team.filter(t=>t.active).length}</strong><span>Ativas</span></div><div><strong>${money(commission)}</strong><span>Comissões recebidas</span></div></div></section></div><div class="filters"><div class="segmented">${[1,2,3].map(n=>`<button class="${level===n?'selected':''}" data-action="level" data-level="${n}">Nível ${n} · ${percent(data.settings.commission_bps[n-1])}</button>`).join('')}</div><form id="search-form"><input name="search" value="${esc(q)}" placeholder="Buscar pessoa" aria-label="Buscar pessoa"></form></div><div class="team-list">${ts.map(t=>`<article class="team-person"><span class="avatar">${esc(t.full_name[0])}</span><div><h3>${esc(t.full_name)}</h3>${status(t.active?'active':'pending')}<p class="muted">${t.products.map(p=>esc(p.name)).join(', ')||'Sem produtos'} · Comissão: ${money(data.commissions.filter(c=>c.source_user_id===t.id).reduce((n,c)=>n+c.amount_cents,0))}</p></div><div class="team-actions">${t.whatsapp?`<a class="secondary" href="https://wa.me/${esc(t.whatsapp)}?text=${encodeURIComponent('Olá! Podemos conversar sobre os seus produtos na Eletrify?')}" target="_blank" rel="noopener noreferrer">WhatsApp</a>`:'<small>Contato não compartilhado</small>'}${button('Doar saldo','transfer',`data-id="${t.id}"`,'secondary')}${button('Presentear','gift',`data-id="${t.id}"`,'secondary')}</div></article>`).join('')||empty('Nenhuma pessoa neste nível','Compartilhe seu link para começar sua equipe.')}</div><p class="footnote">Ativo: possui produto ativo. Contatos aparecem quando a pessoa autoriza. Comissão concedida uma vez, sobre a primeira unidade da primeira compra própria; presentes não geram comissão.</p>`;}
function walletPage(){return `${heading('Carteira','Consulte seu saldo e o histórico de movimentações.')}<div class="wallet-top"><section class="balance-card"><span class="card-label">Saldo disponível</span><div class="balance">${money(data.wallet.available_cents)}</div><p>${money(data.wallet.reserved_cents)} reservados</p><div class="button-row">${button('Adicionar saldo','deposit')}${button('Solicitar saque','withdraw','','secondary')}</div></section><div class="wallet-rules panel"><h3>Depósitos e saques</h3><p>Depósitos de <strong>R$35 a R$5.000</strong>.</p><p>Saques de <strong>R$30 a R$10.000</strong>, uma solicitação por dia.</p><p>Taxa de <strong>5%</strong> descontada do valor solicitado.</p>${status(data.settings.withdrawals_enabled?'active':'paused')}<small>Saques ${data.settings.withdrawals_enabled?'habilitados':'desativados'} · aprovação administrativa</small></div></div><section class="panel"><div class="section-heading"><h2>Depósitos e saques</h2></div>${transactionTable()}</section><section class="panel"><div class="section-heading"><h2>Extrato do saldo</h2><select id="ledger-filter" aria-label="Filtrar extrato"><option value="">Todas as movimentações</option value="deposit">Depósitos</option><option value="yield">Rendimentos</option><option value="principal_return">Devolução do capital</option><option value="purchase">Compras</option><option value="transfer">Transferências</option><option value="commission">Comissões</option><option value="withdrawal">Saques</option></select></div>${ledgerTable()}</section>`;}
function transactionTable(){const rows=[...data.deposits.map(d=>({...d,type:'Depósito'})),...data.withdrawals.map(w=>({...w,type:'Saque'}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return rows.length?`<div class="table-scroll"><table><thead><tr><th>Operação</th><th>Solicitado</th><th>Líquido / taxa</th><th>Status</th><th>Data</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.type}</td><td>${money(x.amount_cents)}</td><td>${x.type==='Saque'?money(x.payout_cents)+' / '+money(x.fee_cents):money(x.amount_cents)}</td><td>${status(x.status)}</td><td>${date(x.created_at)}</td><td>${x.type==='Depósito'&&['pending','review','creating'].includes(x.status)?`<button class="text" data-action="open-deposit" data-id="${x.id}">Ver Pix</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Sem movimentações','Seus depósitos e saques aparecerão aqui.');}
function ledgerTable(){return data.ledger.length?`<div class="table-scroll"><table id="ledger-table"><thead><tr><th>Movimentação</th><th>Valor</th><th>Data</th></tr></thead><tbody>${data.ledger.map(x=>`<tr data-kind="${esc(x.kind)}"><td>${esc(x.description)}</td><td class="${x.amount_cents>0?'positive':''}">${money(x.amount_cents)}</td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table></div>`:empty('Extrato vazio','Cada movimentação de saldo será registrada aqui.');}
function adminPage(){const a=data.admin;if(!a)return empty('Acesso negado','Apenas administradores podem acessar esta área.');const ts=[['overview','Resumo'],['products','Produtos'],['users','Usuários'],['positions','Produtos dos usuários'],['withdrawals','Saques'],['settings','Configurações'],['audit','Auditoria']];let body='';
 if(adminTab==='overview')body=`<div class="metrics">${[['Usuários',a.users.length],['Produtos ativos',a.positions.filter(p=>p.status==='active').length],['Saques aguardando',a.withdrawals.filter(w=>w.status==='requested').length]].map(([t,n])=>`<div class="metric"><span>${t}</span><strong>${n}</strong></div>`).join('')}</div><section class="panel"><h2>Estado da operação</h2><div class="overview-grid"><div><p>Saques ${status(data.settings.withdrawals_enabled?'active':'paused')}</p><p>Reservado: <strong>${money(a.users.reduce((n,u)=>n+u.wallet.reserved_cents,0))}</strong></p><p>Saldo disponível dos usuários: <strong>${money(a.users.reduce((n,u)=>n+u.wallet.available_cents,0))}</strong></p></div><div><p>Depósitos confirmados: <strong>${a.deposits.filter(d=>d.status==='completed').length}</strong></p><p>Webhooks em análise: <strong>${a.webhooks.filter(w=>w.status==='review').length}</strong></p><button class="secondary" data-action="process">Processar saques aprovados</button></div></div></section>`;
 if(adminTab==='products')body=`<div class="section-heading"><h2>Catálogo</h2>${button('Adicionar produto','admin-product')}</div><div class="table-scroll panel"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Taxa / prazo</th><th>Status</th><th></th></tr></thead><tbody>${data.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${labels[p.category]}</td><td>${money(p.price_cents)}</td><td>${percent(p.daily_bps)} / ${p.duration_days} dias</td><td>${status(p.active?'active':'paused')}</td><td><button class="text" data-action="admin-product" data-id="${p.id}">Editar</button></td></tr>`).join('')}</tbody></table></div>`;
 if(adminTab==='users')body=`<div class="section-heading"><h2>Usuários</h2><form id="search-form"><input name="search" placeholder="Buscar usuário" value="${esc(q)}"></form></div><div class="table-scroll panel"><table><thead><tr><th>Nome / contato</th><th>Saldo disponível</th><th>Reservado</th><th>Status</th><th>Ações</th></tr></thead><tbody>${a.users.filter(u=>u.full_name.toLowerCase().includes(q.toLowerCase())).map(u=>`<tr><td><strong>${esc(u.full_name)}</strong><small>${esc(u.email||u.whatsapp||'Sem contato')}</small></td><td>${money(u.wallet.available_cents)}</td><td>${money(u.wallet.reserved_cents)}</td><td>${status(u.blocked?'paused':'active')}</td><td><div class="table-actions"><button class="text" data-action="admin-user" data-id="${u.id}">Perfil</button><button class="text" data-action="admin-balance" data-id="${u.id}">Saldo</button><button class="text" data-action="admin-add-position" data-id="${u.id}">Produto</button></div></td></tr>`).join('')}</tbody></table></div>`;
 if(adminTab==='positions')body=`<div class="table-scroll panel"><table><thead><tr><th>Usuário</th><th>Produto</th><th>Capital</th><th>Recebido</th><th>Taxa / períodos</th><th>Status</th><th></th></tr></thead><tbody>${a.positions.map(p=>`<tr><td>${esc(a.users.find(u=>u.id===p.user_id)?.full_name||p.user_id)}</td><td>${esc(p.name)}</td><td>${money(p.principal_cents)}</td><td>${money(p.earned_cents)}</td><td>${percent(p.daily_bps)} · ${p.paid_periods}/${p.duration_days}</td><td>${status(p.status)}</td><td><button class="text" data-action="admin-position" data-id="${p.id}">Editar</button></td></tr>`).join('')}</tbody></table></div>`;
 if(adminTab==='withdrawals')body=`<div class="section-heading"><h2>Solicitações de saque</h2><div class="button-row">${button('Aprovar selecionados','approve-selected','','secondary')}${button('Aprovar todos pendentes','approve-all')}${button('Processar aprovados','process','','secondary')}</div></div><div class="table-scroll panel"><table><thead><tr><th><input id="select-all" type="checkbox" aria-label="Selecionar todos"></th><th>Usuário</th><th>Solicitado / líquido</th><th>Pix</th><th>Status</th><th>Data</th><th></th></tr></thead><tbody>${a.withdrawals.map(w=>`<tr><td>${w.status==='requested'?`<input class="withdraw-select" type="checkbox" value="${w.id}" aria-label="Selecionar saque">`:''}</td><td>${esc(a.users.find(u=>u.id===w.user_id)?.full_name||w.user_id)}</td><td>${money(w.amount_cents)}<small>Líquido ${money(w.payout_cents)} · taxa ${money(w.fee_cents)}</small></td><td>${esc(w.pix_key)}<small>${esc(w.pix_key_type)}</small></td><td>${status(w.status)}${w.last_error?`<small>${esc(w.last_error)}</small>`:''}</td><td>${date(w.created_at)}</td><td>${w.status==='review'?`<button class="text" data-action="retry-withdrawal" data-id="${w.id}">Reprocessar</button>`:''}${w.status==='requested'?`<button class="text" data-action="approve" data-id="${w.id}">Aprovar</button> <button class="text danger" data-action="reject" data-id="${w.id}">Rejeitar</button>`:''}</td></tr>`).join('')}</tbody></table>${a.withdrawals.length?'':empty('Nenhum saque solicitado','As solicitações chegarão nesta área.')}</div>`;
 if(adminTab==='settings')body=`<section class="panel form-panel"><h2>Configurações da plataforma</h2><form data-form="settings"><label class="check-label"><input type="checkbox" name="withdrawals_enabled" ${data.settings.withdrawals_enabled?'checked':''}> Permitir saques e processamento de aprovados</label><div class="form-grid">${field('Comissão nível 1 (%)','level1',data.settings.commission_bps[0]/100,'number','min="0" max="100" step="0.01" required')}${field('Comissão nível 2 (%)','level2',data.settings.commission_bps[1]/100,'number','min="0" max="100" step="0.01" required')}${field('Comissão nível 3 (%)','level3',data.settings.commission_bps[2]/100,'number','min="0" max="100" step="0.01" required')}</div>${field('Grupo oficial do WhatsApp','whatsapp_group',data.settings.whatsapp_group,'url','placeholder="https://chat.whatsapp.com/..."')}<label class="check-label"><input name="return_principal" type="checkbox" ${data.settings.return_principal?'checked':''}> Devolver o valor investido no vencimento (novas compras)</label><p class="muted">Condições alteradas valem para novas compras. Produtos existentes mantêm o contrato salvo na aquisição. Saque: uma solicitação por dia, limite de R$30–R$10.000 e taxa de 5%.</p><button class="primary">Salvar configurações</button></form></section>`;
 if(adminTab==='audit')body=`<section class="panel"><h2>Histórico administrativo</h2><div class="table-scroll"><table><thead><tr><th>Ação</th><th>Data</th><th>Detalhes</th></tr></thead><tbody>${a.audit.map(x=>`<tr><td>${esc(x.action)}</td><td>${date(x.created_at)}</td><td><details><summary>Ver registro</summary><pre>${esc(JSON.stringify(x.details,null,2))}</pre></details></td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>Webhooks</h2><div class="table-scroll"><table><thead><tr><th>Entrega / evento</th><th>Status</th><th>Erro</th></tr></thead><tbody>${a.webhooks.map(x=>`<tr><td>${esc(x.delivery_id)}<small>${esc(x.event)}</small></td><td>${status(x.status)}</td><td>${esc(x.last_error||'—')}${x.status==='review'?`<button class="text" data-action="retry-event" data-id="${esc(x.delivery_id)}">Reprocessar</button>`:''}</td></tr>`).join('')}</tbody></table></div></section>`;
 return `${heading('Administração','Controle da plataforma, condições e solicitações.')}<div class="admin-tabs">${ts.map(([k,l])=>`<button data-action="admin-tab" data-tab="${k}" class="${adminTab===k?'selected':''}">${l}</button>`).join('')}</div>${body}`;
}
function modal(title,content){const d=$('#modal');d.innerHTML=`<div class="modal-heading"><h2>${title}</h2><button data-action="close" aria-label="Fechar">×</button></div>${content}<div class="form-error" role="alert"></div>`;d.showModal();bind(d);d.onclick=e=>{if(e.target===d)d.close();};}
function productModal(id,gift=null){const p=data.products.find(p=>p.id===id);modal(gift?'Presentear com produto':p.name,`<img class="modal-product" src="${esc(p.image)}" alt="${esc(p.name)}"><p class="muted">${esc(p.description)}</p><div class="terms-box"><div><span>Preço à vista</span><strong>${money(p.price_cents)}</strong></div><div><span>Taxa por 24h</span><strong>${percent(p.daily_bps)}</strong></div><div><span>Duração</span><strong>${p.duration_days} dias</strong></div><div><span>Rendimentos estimados por unidade</span><strong>${money(dailyYield(p.price_cents,p.daily_bps)*p.duration_days)}</strong></div><div><span>Capital devolvido no vencimento</span><strong>${data.settings.return_principal?money(p.price_cents):'Não previsto neste contrato'}</strong></div><div><span>Total estimado por unidade</span><strong>${money(dailyYield(p.price_cents,p.daily_bps)*p.duration_days+(data.settings.return_principal?p.price_cents:0))}</strong></div></div><p class="muted">O valor investido ${data.settings.return_principal?'será devolvido ao saldo no vencimento, além dos rendimentos':'não tem devolução prevista neste contrato'}. Saldo disponível: ${money(data.wallet.available_cents)}.</p><form data-form="buy" data-id="${id}" ${gift?`data-user="${gift}"`:''}>${field('Quantidade','quantity',1,'number','min="1" max="100" required')}<label class="check-label"><input type="checkbox" required> Li e aceito as condições exibidas para esta aquisição.</label><button class="primary">${gift?'Comprar presente':'Confirmar compra'}</button></form>`);}
function withdrawalModal(){if(!data.settings.withdrawals_enabled)return modal('Saques pausados','<p>Os saques estão desativados no momento. Consulte novamente mais tarde.</p>');modal('Solicitar saque',`<p class="muted">Saldo: ${money(data.wallet.available_cents)} · Uma solicitação por dia.</p><form data-form="withdraw">${field('Valor solicitado (R$)','amount','','number','min="30" max="10000" step="0.01" required')}${select('Tipo de chave','pix_key_type','cpf',[['cpf','CPF'],['cnpj','CNPJ'],['email','E-mail'],['phone','Telefone'],['evp','Chave aleatória']])}${field('Chave Pix','pix_key','','text','required maxlength="200"')}${field('CPF/CNPJ do destinatário','recipient_document','','text','required placeholder="Somente números"')}<div id="payout-preview" class="notice">Taxa de 5% descontada do valor solicitado.</div><button class="primary">Solicitar saque</button></form>`);$('[name=amount]').addEventListener('input',e=>{try{const p=payout(toCents(e.target.value));$('#payout-preview').textContent=`Débito ${money(p.amount_cents)} · Taxa ${money(p.fee_cents)} · Você recebe ${money(p.payout_cents)}`;}catch{}});}
function depositModal(){modal('Adicionar saldo',`<p class="muted">Depósito via Pix, de R$35 a R$5.000. O saldo será creditado após a confirmação.</p><form data-form="deposit">${field('Valor em reais','amount','','number','min="35" max="5000" step="0.01" required')}<button class="primary">Gerar cobrança Pix</button></form>`);}
function showDeposit(d){modal('Depósito Pix',`${status(d.status)}<h3>${money(d.amount_cents)}</h3>${isDemo()?'<div class="notice">Demonstração: nenhum QR Code de pagamento real é gerado. O botão abaixo simula a confirmação apenas nesta prévia.</div>':d.qr_code_image&&/^data:image\/(png|jpeg);base64,/.test(d.qr_code_image)?`<img class="qr" src="${esc(d.qr_code_image)}" alt="QR Code Pix">`:'<p>A cobrança está sendo conciliada. Aguarde a confirmação da gateway.</p>'}${d.qr_code?`<div class="copy-line"><input readonly value="${esc(d.qr_code)}" aria-label="Pix copia e cola"><button data-action="copy" data-copy="${esc(d.qr_code)}">Copiar Pix</button></div>`:''}<button class="primary" data-action="check-deposit" data-id="${d.id}">${isDemo()?'Simular confirmação':'Verificar pagamento'}</button><p class="muted">Não crie outra cobrança se a geração anterior ficou incerta. Confira seu histórico.</p>`);}
function profileModal(){modal('Seu perfil',`<form data-form="profile">${field('Nome completo','full_name',data.profile.full_name,'text','minlength="2" required')}${field('WhatsApp','whatsapp',data.profile.whatsapp,'tel','required')}${field('Foto do perfil (URL HTTPS, opcional)','avatar_url',data.profile.avatar_url||'','url')}<label class="check-label"><input type="checkbox" name="contact_consent" ${data.profile.contact_consent?'checked':''}> Compartilhar meu WhatsApp com a minha equipe de indicação.</label><button class="primary">Salvar perfil</button></form><hr><form data-form="email">${field('Novo e-mail','email','','email','required')}<button class="secondary">Alterar e-mail</button></form><hr><form data-form="password">${field('Nova senha','password','','password','minlength="8" required')}${field('Confirmar nova senha','repeat','','password','minlength="8" required')}<button class="secondary">Alterar senha</button></form>`);}
function adminProduct(id){const p=data.products.find(x=>x.id===id)||{name:'',category:'production',price_cents:0,daily_bps:500,duration_days:10,image:'/assets/patinete-bateria-componentes.png',active:false};modal(id?'Editar produto':'Novo produto',`<form data-form="admin-product" data-id="${id||''}">${field('Nome','name',p.name,'text','required')}${select('Categoria','category',p.category,[['production','Produção'],['distribution','Distribuição']])}${field('Descrição','description',p.description||'')}<div class="form-grid">${field('Preço (R$)','price',p.price_cents/100,'number','min="0.01" step="0.01" required')}${field('Taxa diária (%)','rate',p.daily_bps/100,'number','min="0" max="100" step="0.01" required')}${field('Prazo (dias)','duration_days',p.duration_days,'number','min="1" max="3650" required')}</div>${field('Imagem (caminho /assets ou URL HTTPS)','image',p.image,'text','required')}<label class="check-label"><input type="checkbox" name="active" ${p.active?'checked':''}> Produto disponível para compra</label><button class="primary">Salvar produto</button></form>`);if(!id){const duration=$('#modal [name=duration_days]');let custom=false;duration.addEventListener('input',()=>{custom=true;});$('#modal [name=category]').addEventListener('change',e=>{if(!custom)duration.value=e.target.value==='distribution'?'15':'10';});}}
function adminUser(id){const u=data.admin.users.find(x=>x.id===id);modal('Perfil de '+esc(u.full_name),`<form data-form="admin-user" data-id="${id}">${field('Nome','full_name',u.full_name,'text','required minlength="2"')}${field('WhatsApp','whatsapp',u.whatsapp,'tel','required')}<label class="check-label"><input type="checkbox" name="blocked" ${u.blocked?'checked':''}> Suspender acesso à plataforma</label><button class="primary">Salvar perfil</button></form><hr><form data-form="admin-email" data-id="${id}">${field('Alterar e-mail da conta','email',u.email||'','email','required')}${field('Motivo','reason','','text','minlength="5" required')}<button class="secondary">Atualizar e-mail</button></form><button class="text" data-action="admin-reset-password" data-id="${id}">Enviar recuperação de senha ao usuário</button>`);}
function bind(root=document){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=async e=>{e.preventDefault();const act=b.dataset.action;try{
 if(act==='navigate')return navigate(b.dataset.route);if(act==='category'){category=b.dataset.category;return render();}if(act==='level'){level=Number(b.dataset.level);return render();}if(act==='banner'){bannerIndex=Number(b.dataset.index);return render();}if(act==='admin-tab'){adminTab=b.dataset.tab;q='';return render();}if(act==='theme')return theme();if(act==='refresh')return await refresh();if(act==='close')return $('#modal').close();if(act==='copy'){await navigator.clipboard.writeText(b.dataset.copy);return toast('Copiado.');}if(act==='logout'){if(isDemo()){leaveDemo();data=null;return renderAuth();}await client.auth.signOut();data=null;return renderAuth();}if(act==='reset-demo'){data=resetDemo();return render();}if(act==='deposit')return depositModal();if(act==='withdraw')return withdrawalModal();if(act==='product')return productModal(b.dataset.id);if(act==='open-deposit')return showDeposit(data.deposits.find(d=>d.id===b.dataset.id));if(act==='profile')return profileModal();if(act==='check-deposit'){b.disabled=true;await payment('check_deposit',{id:b.dataset.id});$('#modal').close();await refresh();return toast(isDemo()?'Depósito simulado confirmado.':'Pagamento consultado. Confira o status no histórico.');}
 if(act==='position'){const p=data.positions.find(p=>p.id===b.dataset.id);return modal(esc(p.name),`<div class="terms-box"><div><span>Valor investido</span><strong>${money(p.principal_cents)}</strong></div><div><span>Taxa contratada / prazo</span><strong>${percent(p.daily_bps)} / ${p.duration_days} dias</strong></div><div><span>Rendimentos recebidos</span><strong>${money(p.earned_cents)}</strong></div><div><span>Vencimento contratado</span><strong>${date(maturity(p))}</strong></div><div><span>Devolução do capital</span><strong>${p.principal_returned?'Concluída · '+money(p.principal_cents):p.return_principal?'Prevista · '+money(p.principal_cents):'Não prevista'}</strong></div><div><span>Próximo rendimento</span><strong>${p.paid_periods<p.duration_days&&['active','paused'].includes(p.status)?date(new Date(Date.parse(p.created_at)+(p.paid_periods+1)*86400000).toISOString()):'Sem períodos pendentes'}</strong></div></div>${status(p.status)}<p>Os rendimentos usam períodos de 24h desde a aquisição. ${p.return_principal?'O valor investido é devolvido ao saldo ao concluir o prazo do contrato.':'Este contrato não prevê devolução adicional do capital.'} ${p.status==='paused'?'O processamento está pausado.':p.status==='cancelled'?'O contrato está cancelado e não recebe novos créditos.':''}</p>`);}
 if(act==='whatsapp')return modal('Comunidade Eletrify',`<p>Converse com a comunidade no grupo oficial.</p>${data.settings.whatsapp_group?`<a class="primary link-button" href="${esc(data.settings.whatsapp_group)}" target="_blank" rel="noopener noreferrer">Entrar no grupo</a>`:'<div class="notice">O grupo oficial ainda não foi configurado.</div>'}`);
 if(act==='invite-tips')return modal('Apresente a Eletrify',`<p>Compartilhe o catálogo, explique preços, prazos e condições. Diferencie estimativas de valores recebidos e deixe a pessoa decidir.</p><div class="notice">“Oi! Conheça a Eletrify e veja os projetos de produção e distribuição. Confira as condições de cada produto e tire suas dúvidas antes de participar: ${esc(location.origin+'/?ref='+data.profile.referral_code)}”</div><p>Não prometa ganhos garantidos nem use contatos sem autorização.</p>`);
 if(act==='transfer')return modal('Doar saldo à equipe',`<p>Destinatário: ${esc(data.team.find(t=>t.id===b.dataset.id).full_name)}. Limite agregado de R$100 por dia.</p><form data-form="transfer" data-id="${b.dataset.id}">${field('Valor (R$)','amount','','number','min="0.01" max="100" step="0.01" required')}<button class="primary">Confirmar doação</button></form>`);
 if(act==='gift')return modal('Escolha um presente',`<div class="gift-options">${data.products.filter(p=>p.active).map(p=>`<button data-action="gift-product" data-id="${p.id}" data-user="${b.dataset.id}"><img src="${esc(p.image)}" alt=""><span>${esc(p.name)}<small>${money(p.price_cents)}</small></span></button>`).join('')}</div>`);
 if(act==='gift-product'){$('#modal').close();return productModal(b.dataset.id,b.dataset.user);}
 if(act==='admin-product')return adminProduct(b.dataset.id);if(act==='admin-user')return adminUser(b.dataset.id);
 if(act==='admin-balance'){const u=data.admin.users.find(u=>u.id===b.dataset.id);return modal('Ajustar saldo disponível',`<p>${esc(u.full_name)} · Saldo reservado ${money(u.wallet.reserved_cents)} permanece vinculado aos saques.</p><form data-form="admin-balance" data-id="${u.id}">${field('Novo saldo disponível (R$)','amount',u.wallet.available_cents/100,'number','min="0" step="0.01" required')}${field('Motivo do ajuste','reason','','text','required minlength="5"')}<button class="primary">Registrar ajuste</button></form>`);}
 if(act==='admin-add-position')return modal('Adicionar produto ao usuário',`<form data-form="admin-add-position" data-id="${b.dataset.id}">${select('Produto','product_id','',data.products.map(p=>[p.id,p.name]))}${field('Motivo da concessão','reason','','text','required minlength="5"')}<p class="muted">Concessão administrativa sem débito do usuário e sem comissão.</p><button class="primary">Conceder produto</button></form>`);
 if(act==='admin-position'){const p=data.admin.positions.find(p=>p.id===b.dataset.id);return modal('Editar posição',`<p>${esc(p.name)} · ${p.paid_periods} períodos já pagos. Pagamentos anteriores permanecem no extrato.</p><form data-form="admin-position" data-id="${p.id}">${select('Status','status',p.status,[['active','Ativo'],['paused','Pausado'],['completed','Concluído'],['cancelled','Cancelado']])}${field('Taxa dos próximos períodos (%)','rate',p.daily_bps/100,'number','min="0" max="100" step="0.01" required')}${field('Duração total (dias)','duration_days',p.duration_days,'number',`min="${Math.max(1,p.paid_periods)}" max="3650" required`)}${field('Motivo','reason','','text','required minlength="5"')}<button class="primary">Salvar alteração auditada</button></form>`);}
 if(['approve','approve-selected','approve-all'].includes(act)){const ids=act==='approve'?[b.dataset.id]:act==='approve-all'?data.admin.withdrawals.filter(w=>w.status==='requested').map(w=>w.id):$$('.withdraw-select:checked').map(x=>x.value);if(!ids.length)throw new Error('Selecione um saque pendente');return modal('Aprovar saques',`<p>Autorizar ${ids.length} solicitação(ões), total de ${money(data.admin.withdrawals.filter(w=>ids.includes(w.id)).reduce((n,w)=>n+w.amount_cents,0))}. O processamento envia Pix reais no ambiente conectado.</p><form data-form="approve" data-ids="${esc(JSON.stringify(ids))}"><button class="primary">Confirmar aprovação</button></form>`);}
 if(act==='reject')return modal('Rejeitar saque',`<form data-form="reject" data-id="${b.dataset.id}">${field('Motivo da rejeição','reason','','text','required minlength="5"')}<p>O valor reservado será devolvido ao saldo disponível.</p><button class="primary">Rejeitar e devolver saldo</button></form>`);
 if(act==='process'){b.disabled=true;await payment('process_approved');await refresh();return toast('Processamento solicitado. Confira os status.');}
 if(act==='retry-event'){await action('admin_retry_event',{delivery_id:b.dataset.id});await refresh();return toast('Evento reenviado para análise.');}
 if(act==='retry-withdrawal')return modal('Reprocessar saque em análise',`<p>A referência original será preservada. Confira a causa da falha antes de autorizar.</p><form data-form="retry-withdrawal" data-id="${b.dataset.id}">${field('Motivo','reason','','text','required minlength="5"')}<button class="primary">Autorizar nova tentativa</button></form>`);
 if(act==='admin-reset-password'){await payment('admin_reset_password',{user_id:b.dataset.id});return toast('Instruções de recuperação solicitadas.');}
 }catch(e){toast(errorMessage(e),true);}finally{if(b.isConnected)b.disabled=false;}});
 root.querySelectorAll('form[data-form]').forEach(f=>f.onsubmit=submit);
 const sf=root.querySelector('#search-form');if(sf)sf.onsubmit=e=>{e.preventDefault();q=new FormData(sf).get('search');render();};
 root.querySelector('#ledger-filter')?.addEventListener('change',e=>{$$('#ledger-table tbody tr').forEach(tr=>tr.hidden=!!e.target.value&&!tr.dataset.kind.includes(e.target.value));});
 root.querySelector('#select-all')?.addEventListener('change',e=>$$('.withdraw-select').forEach(c=>c.checked=e.target.checked));
}
async function submit(e){e.preventDefault();if(busy)return;busy=true;const f=e.target,d=Object.fromEntries(new FormData(f)),type=f.dataset.form,btn=f.querySelector('button[type=submit],button.primary,button.secondary');if(btn)btn.disabled=true;
 try{let name='',args={};
 if(type==='buy'){const p=data.products.find(p=>p.id===f.dataset.id);if(p.price_cents*Number(d.quantity)>data.wallet.available_cents){$('#modal').close();depositModal();throw new Error('Saldo insuficiente. Adicione saldo para adquirir este produto.');}name=f.dataset.user?'gift':'purchase';args={product_id:p.id,quantity:Number(d.quantity),user_id:f.dataset.user||data.profile.id};}
 if(type==='withdraw'){const amount=toCents(d.amount);if(amount<3000||amount>1000000)throw new Error('Saque entre R$30 e R$10.000');name='withdrawal';args={amount_cents:amount,pix_key:d.pix_key.trim(),pix_key_type:d.pix_key_type,recipient_document:d.recipient_document.replace(/\D/g,'')};}
 if(type==='deposit'){const amount=toCents(d.amount);if(amount<3500||amount>500000)throw new Error('Depósito entre R$35 e R$5.000');const out=await payment('create_deposit',{amount_cents:amount,request_id:crypto.randomUUID()});data=await snapshot(route==='admin');$('#modal').close();render();showDeposit(out.deposit);return;}
 if(type==='transfer'){name='transfer';args={user_id:f.dataset.id,amount_cents:toCents(d.amount)};}
 if(type==='profile'){name='profile';args={...d,contact_consent:!!d.contact_consent};}
 if(type==='email'||type==='password'){
 if(isDemo())throw new Error('E-mail e senha reais são alterados no ambiente conectado.');if(type==='password'&&d.password!==d.repeat)throw new Error('As senhas precisam ser iguais.');const {error}=await client.auth.updateUser(type==='email'?{email:d.email}:{password:d.password});if(error)throw error;$('#modal').close();toast(type==='email'?'Confirme a alteração no e-mail enviado.':'Senha atualizada.');return;}
 if(type==='admin-email'){await payment('admin_update_email',{user_id:f.dataset.id,email:d.email,reason:d.reason});$('#modal').close();await refresh();toast('E-mail atualizado pelo administrador.');return;}
 if(type==='admin-product'){if(!/^\/assets\/[^<>]+$|^https:\/\/[^<>]+$/.test(d.image))throw new Error('Use um caminho /assets ou URL HTTPS');name='admin_product';args={...d,id:f.dataset.id||null,price_cents:toCents(d.price),daily_bps:toCents(d.rate),duration_days:Number(d.duration_days),active:!!d.active};}
 if(type==='settings'){name='admin_settings';args={withdrawals_enabled:!!d.withdrawals_enabled,return_principal:!!d.return_principal,level1_bps:toCents(d.level1),level2_bps:toCents(d.level2),level3_bps:toCents(d.level3),whatsapp_group:d.whatsapp_group};}
 if(type==='admin-user'){name='admin_user';args={...d,user_id:f.dataset.id,blocked:!!d.blocked};}
 if(type==='admin-balance'){name='admin_balance';args={user_id:f.dataset.id,amount_cents:toCents(d.amount),reason:d.reason};}
 if(type==='admin-add-position'){name='admin_position';args={user_id:f.dataset.id,product_id:d.product_id,reason:d.reason};}
 if(type==='admin-position'){name='admin_position';args={id:f.dataset.id,status:d.status,daily_bps:toCents(d.rate),duration_days:Number(d.duration_days),reason:d.reason};}
 if(type==='approve'){name='admin_approve';args={ids:JSON.parse(f.dataset.ids)};}if(type==='reject'){name='admin_reject';args={ids:[f.dataset.id],reason:d.reason};}
 if(type==='retry-withdrawal'){name='admin_retry_withdrawal';args={id:f.dataset.id,reason:d.reason};}
 await action(name,args);$('#modal')?.close();await refresh();toast('Operação concluída.');
 }catch(e){if($('#modal')?.open&&$('#modal .form-error'))$('#modal .form-error').textContent=errorMessage(e);else toast(errorMessage(e),true);}finally{busy=false;if(btn?.isConnected)btn.disabled=false;}
}
function renderAuth(){const m=authMode;app.innerHTML=`<div class="auth-layout"><aside class="auth-story"><img class="auth-logo" src="/assets/logo.png" alt="Eletrify"><div><span class="eyebrow">MOBILIDADE · TECNOLOGIA · FUTURO</span><h1>O próximo movimento<br>começa com você.</h1><p>Sua conta, seus produtos e sua equipe.<br>Conectados em um só lugar.</p></div><img class="auth-hero" src="/assets/hero.png" alt="Ilustração de mobilidade elétrica"><small>Eletrify · Conectada ao futuro.</small></aside><section class="auth-access"><header><span>PORTAL ELETRIFY</span><button id="auth-theme" class="icon-btn" aria-label="Alternar tema">${icon('sun')}</button></header><div class="auth-form"><span class="eyebrow">${m==='register'?'FAÇA PARTE':'ACESSO À CONTA'}</span><h2>${{login:'Entre na sua conta',register:'Crie sua conta',forgot:'Esqueceu sua senha?',confirm:'Confira seu e-mail',reset:'Escolha uma nova senha'}[m]}</h2><p>${m==='forgot'?'Enviaremos um link para redefinir sua senha.':m==='confirm'?'Confirme seu cadastro pela mensagem enviada.':'Bem-vindo à Eletrify.'}</p>${!client?'<div class="notice">A prévia pode ser explorada em demonstração. O acesso real depende da configuração do Supabase.</div>':''}<form id="auth-form">${m==='register'?field('Nome completo','name','','text','autocomplete="name" minlength="2" required')+field('WhatsApp com DDD','phone','','tel','autocomplete="tel" required'):''}${m!=='reset'?field('E-mail','email','','email','autocomplete="email" required'):''}${['login','register','reset'].includes(m)?field('Senha','password','','password','minlength="8" required autocomplete="'+(m==='login'?'current-password':'new-password')+'"'):''}${['register','reset'].includes(m)?field('Confirmar senha','repeat','','password','minlength="8" required'):''}${m==='register'?field('Código de indicação (opcional)','ref',new URLSearchParams(location.search).get('ref')||'')+'<label class="check-label"><input type="checkbox" name="contact_consent"> Compartilhar meu WhatsApp com minha equipe de indicação.</label>':''}${m==='login'?'<button class="text right" type="button" data-auth="forgot">Esqueceu sua senha?</button>':''}<button class="primary" ${!client?'disabled':''}>${{login:'Entrar',register:'Criar conta',forgot:'Enviar link',reset:'Salvar senha',confirm:'Reenviar confirmação'}[m]}</button></form><div class="auth-switch">${m==='login'?'Ainda não tem conta? <button class="text" data-auth="register">Criar conta</button>':'<button class="text" data-auth="login">Voltar para entrar</button>'}</div>${!client?'<button id="demo-button" class="secondary full">Explorar demonstração completa</button>':''}<div id="auth-message" role="status"></div></div><footer>© ${new Date().getFullYear()} Eletrify</footer></section></div>`;
 $('#auth-theme').onclick=theme;$$('[data-auth]').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;renderAuth();});$('#demo-button')?.addEventListener('click',()=>{data=enterDemo();route=(location.hash==='#/admin'||location.pathname==='/admin')?'admin':'dashboard';render();});$('#auth-form').onsubmit=authSubmit;
}
async function authSubmit(e){e.preventDefault();if(!client||busy)return;const d=Object.fromEntries(new FormData(e.target));if(d.repeat&&d.password!==d.repeat){$('#auth-message').textContent='As senhas precisam ser iguais.';return;}busy=true;e.target.querySelector('.primary').disabled=true;try{
 let r;const origin=location.origin+'/';if(authMode==='login')r=await client.auth.signInWithPassword({email:d.email,password:d.password});if(authMode==='register')r=await client.auth.signUp({email:d.email,password:d.password,options:{emailRedirectTo:origin,data:{full_name:d.name,whatsapp:d.phone.replace(/\D/g,''),referral_code:d.ref||null,contact_consent:!!d.contact_consent}}});if(authMode==='forgot')r=await client.auth.resetPasswordForEmail(d.email,{redirectTo:origin+'?flow=recovery'});if(authMode==='confirm')r=await client.auth.resend({type:'signup',email:d.email,options:{emailRedirectTo:origin}});if(authMode==='reset'){if(!recovery)throw new Error('Abra um link válido de recuperação.');r=await client.auth.updateUser({password:d.password});}if(r.error)throw r.error;
 if(authMode==='register'&&!r.data.session){authMode='confirm';renderAuth();$('#auth-message').textContent='Confira seu e-mail e a pasta de spam.';}else if(authMode==='reset'){recovery=false;history.replaceState(null,'','/');await client.auth.signOut();authMode='login';renderAuth();$('#auth-message').textContent='Senha atualizada. Entre novamente.';}else if(['forgot','confirm'].includes(authMode))$('#auth-message').textContent='Se o endereço estiver apto, você receberá um e-mail com as instruções.';
 }catch(e){$('#auth-message').textContent=authMode==='login'?'Não foi possível entrar. Confira os dados e confirme seu e-mail.':errorMessage(e);}finally{busy=false;$('#auth-form .primary')?.removeAttribute('disabled');}}
renderAuth();
if(client){client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;authMode='reset';renderAuth();}else if(event==='SIGNED_OUT'){data=null;renderAuth();}else if(session&&!recovery&&!new URLSearchParams(location.search).has('flow'))setTimeout(async()=>{try{route=location.hash.slice(2)||(location.pathname==='/admin'?'admin':'dashboard');if(!names[route])route='dashboard';await refresh();}catch(e){if($('#auth-message'))$('#auth-message').textContent=errorMessage(e);}},0);});client.auth.getSession().then(async({data:{session}})=>{if(new URLSearchParams(location.search).get('flow')==='recovery'){if(session){recovery=true;authMode='reset';renderAuth();}else $('#auth-message').textContent='Link inválido ou expirado. Solicite outro.';}else if(session){try{route=location.hash.slice(2)||(location.pathname==='/admin'?'admin':'dashboard');if(!names[route])route='dashboard';await refresh();}catch(e){$('#auth-message').textContent=errorMessage(e);}}});}
setInterval(()=>{if(data&&route==='dashboard'&&!$('#modal')?.open&&!busy){bannerIndex=(bannerIndex+1)%3;render();}},9000);
setInterval(()=>{if(data&&!$('#modal')?.open&&!busy&&!isDemo())refresh().catch(()=>{});},60000);
